import { ToothInfo, DentalService, ClinicInfo, BeforeAfterCase, ClinicSettings } from '../types';

export const FDI_TEETH: ToothInfo[] = [
  // Upper Right (Quadrant 1) - FDI 18 down to 11
  { fdiNumber: 18, quadrant: 1, nameAr: 'ضرس العقل العلوي الأيمن', nameEn: 'Upper Right 3rd Molar (Wisdom)', type: 'wisdom' },
  { fdiNumber: 17, quadrant: 1, nameAr: 'الضرس الثاني العلوي الأيمن', nameEn: 'Upper Right 2nd Molar', type: 'molar' },
  { fdiNumber: 16, quadrant: 1, nameAr: 'الضرس الأول العلوي الأيمن', nameEn: 'Upper Right 1st Molar', type: 'molar' },
  { fdiNumber: 15, quadrant: 1, nameAr: 'الضاحك الثاني العلوي الأيمن', nameEn: 'Upper Right 2nd Premolar', type: 'premolar' },
  { fdiNumber: 14, quadrant: 1, nameAr: 'الضاحك الأول العلوي الأيمن', nameEn: 'Upper Right 1st Premolar', type: 'premolar' },
  { fdiNumber: 13, quadrant: 1, nameAr: 'الناب العلوي الأيمن', nameEn: 'Upper Right Canine', type: 'canine' },
  { fdiNumber: 12, quadrant: 1, nameAr: 'القاطع الجانبي العلوي الأيمن', nameEn: 'Upper Right Lateral Incisor', type: 'incisor' },
  { fdiNumber: 11, quadrant: 1, nameAr: 'القاطع المركزي العلوي الأيمن', nameEn: 'Upper Right Central Incisor', type: 'incisor' },

  // Upper Left (Quadrant 2) - FDI 21 up to 28
  { fdiNumber: 21, quadrant: 2, nameAr: 'القاطع المركزي العلوي الأيسر', nameEn: 'Upper Left Central Incisor', type: 'incisor' },
  { fdiNumber: 22, quadrant: 2, nameAr: 'القاطع الجانبي العلوي الأيسر', nameEn: 'Upper Left Lateral Incisor', type: 'incisor' },
  { fdiNumber: 23, quadrant: 2, nameAr: 'الناب العلوي الأيسر', nameEn: 'Upper Left Canine', type: 'canine' },
  { fdiNumber: 24, quadrant: 2, nameAr: 'الضاحك الأول العلوي الأيسر', nameEn: 'Upper Left 1st Premolar', type: 'premolar' },
  { fdiNumber: 25, quadrant: 2, nameAr: 'الضاحك الثاني العلوي الأيسر', nameEn: 'Upper Left 2nd Premolar', type: 'premolar' },
  { fdiNumber: 26, quadrant: 2, nameAr: 'الضرس الأول العلوي الأيسر', nameEn: 'Upper Left 1st Molar', type: 'molar' },
  { fdiNumber: 27, quadrant: 2, nameAr: 'الضرس الثاني العلوي الأيسر', nameEn: 'Upper Left 2nd Molar', type: 'molar' },
  { fdiNumber: 28, quadrant: 2, nameAr: 'ضرس العقل العلوي الأيسر', nameEn: 'Upper Left 3rd Molar (Wisdom)', type: 'wisdom' },

  // Lower Left (Quadrant 3) - FDI 38 down to 31
  { fdiNumber: 38, quadrant: 3, nameAr: 'ضرس العقل السفلي الأيسر', nameEn: 'Lower Left 3rd Molar (Wisdom)', type: 'wisdom' },
  { fdiNumber: 37, quadrant: 3, nameAr: 'الضرس الثاني السفلي الأيسر', nameEn: 'Lower Left 2nd Molar', type: 'molar' },
  { fdiNumber: 36, quadrant: 3, nameAr: 'الضرس الأول السفلي الأيسر', nameEn: 'Lower Left 1st Molar', type: 'molar' },
  { fdiNumber: 35, quadrant: 3, nameAr: 'الضاحك الثاني السفلي الأيسر', nameEn: 'Lower Left 2nd Premolar', type: 'premolar' },
  { fdiNumber: 34, quadrant: 3, nameAr: 'الضاحك الأول السفلي الأيسر', nameEn: 'Lower Left 1st Premolar', type: 'premolar' },
  { fdiNumber: 33, quadrant: 3, nameAr: 'الناب السفلي الأيسر', nameEn: 'Lower Left Canine', type: 'canine' },
  { fdiNumber: 32, quadrant: 3, nameAr: 'القاطع الجانبي السفلي الأيسر', nameEn: 'Lower Left Lateral Incisor', type: 'incisor' },
  { fdiNumber: 31, quadrant: 3, nameAr: 'القاطع المركزي السفلي الأيسر', nameEn: 'Lower Left Central Incisor', type: 'incisor' },

  // Lower Right (Quadrant 4) - FDI 41 up to 48
  { fdiNumber: 41, quadrant: 4, nameAr: 'القاطع المركزي السفلي الأيمن', nameEn: 'Lower Right Central Incisor', type: 'incisor' },
  { fdiNumber: 42, quadrant: 4, nameAr: 'القاطع الجانبي السفلي الأيمن', nameEn: 'Lower Right Lateral Incisor', type: 'incisor' },
  { fdiNumber: 43, quadrant: 4, nameAr: 'الناب السفلي الأيمن', nameEn: 'Lower Right Canine', type: 'canine' },
  { fdiNumber: 44, quadrant: 4, nameAr: 'الضاحك الأول السفلي الأيمن', nameEn: 'Lower Right 1st Premolar', type: 'premolar' },
  { fdiNumber: 45, quadrant: 4, nameAr: 'الضاحك الثاني السفلي الأيمن', nameEn: 'Lower Right 2nd Premolar', type: 'premolar' },
  { fdiNumber: 46, quadrant: 4, nameAr: 'الضرس الأول السفلي الأيمن', nameEn: 'Lower Right 1st Molar', type: 'molar' },
  { fdiNumber: 47, quadrant: 4, nameAr: 'الضرس الثاني السفلي الأيمن', nameEn: 'Lower Right 2nd Molar', type: 'molar' },
  { fdiNumber: 48, quadrant: 4, nameAr: 'ضرس العقل السفلي الأيمن', nameEn: 'Lower Right 3rd Molar (Wisdom)', type: 'wisdom' },
];

export const SYMPTOMS_LIST = [
  { id: 'throbbing_pain', labelAr: 'ألم نابض ومستمر', labelEn: 'Throbbing / Continuous Pain', icon: 'zap' },
  { id: 'cold_sensitivity', labelAr: 'حساسية شديدة مع المشروبات الباردة', labelEn: 'Sensitivity to Cold', icon: 'snowflake' },
  { id: 'hot_sensitivity', labelAr: 'ألم عند تناول أطعمة/مشروبات ساخنة', labelEn: 'Sensitivity to Hot', icon: 'flame' },
  { id: 'chewing_pain', labelAr: 'ألم أثناء المضغ أو الضغط على السن', labelEn: 'Pain when Chewing/Biting', icon: 'alert-circle' },
  { id: 'gum_swelling', labelAr: 'تورم أو انتفاخ في اللثة / الوجه', labelEn: 'Gum / Facial Swelling', icon: 'shield-alert' },
  { id: 'bleeding_gums', labelAr: 'نزيف في اللثة عند التفريش', labelEn: 'Bleeding Gums', icon: 'droplet' },
  { id: 'broken_tooth', labelAr: 'كسر أو شرخ في السن / الحشوة', labelEn: 'Broken / Cracked Tooth', icon: 'scissors' },
  { id: 'loose_tooth', labelAr: 'حركة أو تخلخل في السن', labelEn: 'Loose Tooth', icon: 'move' },
  { id: 'night_pain', labelAr: 'ألم يزداد ليلاً ويمنع النوم', labelEn: 'Pain Worsens at Night', icon: 'moon' },
  { id: 'bad_breath_taste', labelAr: 'طعم أو رائحة كريهة مستمرة', labelEn: 'Bad Taste / Odor', icon: 'frown' },
];

export const DEFAULT_SERVICES: DentalService[] = [
  {
    id: 'consultation_checkup',
    nameAr: 'كشف واستشارة طبية شاملة',
    nameEn: 'Comprehensive Dental Consultation',
    descriptionAr: 'فحص سريري كامل للأسنان واللثة مع خطة علاج مخصصة',
    descriptionEn: 'Full clinical dental and periodontal examination with custom treatment plan',
    durationMinutes: 30,
    estimatedPrice: 200,
    iconName: 'stethoscope',
    category: 'checkup',
  },
  {
    id: 'root_canal',
    nameAr: 'علاج وجذور وأعصاب (علاج عصب)',
    nameEn: 'Root Canal Treatment (Endodontics)',
    descriptionAr: 'تنظيف قنوات العصب بأحدث الأجهزة الدوارة وحشو العصب بدقة',
    descriptionEn: 'Rotary root canal therapy with digital length determination',
    durationMinutes: 45,
    estimatedPrice: 900,
    iconName: 'activity',
    category: 'endodontics',
  },
  {
    id: 'cosmetic_filling',
    nameAr: 'حشوات تجميلية كمبوزيت',
    nameEn: 'Cosmetic Composite Restorations',
    descriptionAr: 'حشوات ليزر تجميلية بلون السن الطبيعي ومقاومة للتآكل',
    descriptionEn: 'Tooth-colored high aesthetic composite fillings',
    durationMinutes: 30,
    estimatedPrice: 450,
    iconName: 'sparkles',
    category: 'restoration',
  },
  {
    id: 'teeth_scaling_polishing',
    nameAr: 'تنظيف وتلميع وإزالة الجير',
    nameEn: 'Ultrasonic Scaling & Polishing',
    descriptionAr: 'إزالة الرواسب الجيرية بالموجات فوق الصوتية وتلميع الأسنان',
    descriptionEn: 'Ultrasonic calculus removal and dental polishing',
    durationMinutes: 30,
    estimatedPrice: 350,
    iconName: 'smile',
    category: 'checkup',
  },
  {
    id: 'teeth_whitening',
    nameAr: 'تبييض الأسنان بالليزر (Zoom/Laser)',
    nameEn: 'In-Office Laser Teeth Whitening',
    descriptionAr: 'تبييض احترافي في جلسة واحدة للحصول على ابتسامة ناصعة',
    descriptionEn: 'Single-session professional in-office power whitening',
    durationMinutes: 60,
    estimatedPrice: 1500,
    iconName: 'sun',
    category: 'cosmetics',
  },
  {
    id: 'dental_implants',
    nameAr: 'زراعة الأسنان الفورية',
    nameEn: 'Dental Implants Surgery',
    descriptionAr: 'تعويض الأسنان المفقودة بأفضل الزرعات الألمانية والسويسرية',
    descriptionEn: 'Premium titanium dental implant placement',
    durationMinutes: 60,
    estimatedPrice: 6500,
    iconName: 'anchor',
    category: 'surgery',
  },
  {
    id: 'orthodontics',
    nameAr: 'تقويم الأسنان (شفاف ومعدني)',
    nameEn: 'Orthodontic Treatment (Braces & Clear Aligners)',
    descriptionAr: 'تعديل وتنسيق اصطفاف الأسنان للأطفال والبالغين',
    descriptionEn: 'Alignment correction using metal braces or invisible aligners',
    durationMinutes: 45,
    estimatedPrice: 8000,
    iconName: 'grid',
    category: 'orthodontics',
  },
];

export const CLINIC_INFO: ClinicInfo = {
  nameAr: 'عيادة دكتور كريم أبو بكر للأسنان',
  nameEn: 'Dr. Karim Abo Bakr Dental Clinic',
  doctorNameAr: 'د. كريم أبو بكر',
  doctorNameEn: 'Dr. Karim Abo Bakr',
  doctorTitleAr: 'استشاري جراحة وتجميل وزراعة الأسنان',
  doctorTitleEn: 'Consultant in Dental Surgery, Cosmetics & Implantology',
  addressAr: 'شارع التحرير، برج الأطباء، الدور الرابع - القاهرة',
  addressEn: 'El Tahrir St., Doctors Tower, 4th Floor - Cairo, Egypt',
  phone: '+20 100 123 4567',
  whatsapp: '+201001234567',
  workingDaysAr: 'السبت - الخميس (الجمعة عطلة)',
  workingDaysEn: 'Saturday - Thursday (Friday Closed)',
  workingHoursAr: '12:00 ظهراً - 10:00 مساءً',
  workingHoursEn: '12:00 PM - 10:00 PM',
  mapLatitude: 30.0444,
  mapLongitude: 31.2357,
  experienceYears: 12,
  rating: 4.9,
  reviewCount: 428,
};

export const DEFAULT_CLINIC_SETTINGS: ClinicSettings = {
  id: 'main',
  doctorName: 'د. كريم أبو بكر',
  doctorTitle: 'استشاري طب وجراحة وتجميل وزراعة الأسنان',
  doctorBio: 'تقديم أحدث الحلول العلاجية والتجميلية وزراعة وتجميل الأسنان بأعلى معايير التعقيم العالمية وأحدث التقنيات الرقمية المتقدمة.',
  avatarUrl: '',
  coverImageUrl: '',
  yearsExperience: 12,
  patientsCount: 3500,
  rating: 4.9,
  phoneNumber: '+20 100 123 4567',
  whatsappNumber: '+201001234567',
  locationAddress: 'مصر الجديدة - القاهرة',
  locationMapsUrl: 'https://maps.google.com',
  workingHours: 'السبت - الخميس: 12:00 م - 10:00 م',
  showClinicInfo: true,
  promoBadgeEnabled: true,
  promoBadgeText: '✨ مجاناً لفترة محدودة',
};

export const INITIAL_BEFORE_AFTER_CASES: BeforeAfterCase[] = [
  {
    id: 'case_1',
    titleAr: 'تجميل الابتسامة بعدسات إيماكس (Veneers)',
    titleEn: 'Full Smile Makeover with E-max Veneers',
    categoryAr: 'تجميل الأسنان',
    categoryEn: 'Cosmetics',
    descriptionAr: 'إصلاح التصبغات وتناسق الفك العلوي بـ 8 عدسات إيماكس فائقة النقاء.',
    descriptionEn: 'Correction of deep stains and teeth alignment with 8 ultra-thin E-max veneers.',
    beforeImageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600&q=80',
    dentistName: 'د. كريم أبو بكر',
    durationWeeks: 2,
  },
  {
    id: 'case_2',
    titleAr: 'زراعة فورية للضرس الأمامي مع تاج زركونيا',
    titleEn: 'Immediate Front Implant with Zirconia Crown',
    categoryAr: 'زراعة الأسنان',
    categoryEn: 'Implants',
    descriptionAr: 'تعويض كسر السن الأمامي بزراعة فورية مجهرية وتاج زركونيا مطابق تماماً للون الطبيعي.',
    descriptionEn: 'Replacement of broken anterior tooth with immediate guided implant and matched zirconia crown.',
    beforeImageUrl: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=600&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600&q=80',
    dentistName: 'د. كريم أبو بكر',
    durationWeeks: 8,
  },
  {
    id: 'case_3',
    titleAr: 'تبييض الأسنان بالليزر وتنظيف عميق',
    titleEn: 'Laser Teeth Whitening & Deep Scaling',
    categoryAr: 'تنظيف وتبييض',
    categoryEn: 'Whitening',
    descriptionAr: 'تفتيح درجة الأسنان 6 درجات في جلسة واحدة مدتها 45 دقيقة بدون أي ألم.',
    descriptionEn: '6 shades lighter in a single 45-minute laser session with zero sensitivity.',
    beforeImageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&q=80',
    dentistName: 'د. كريم أبو بكر',
    durationWeeks: 1,
  },
];
